apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-toolkit-view
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - taskruns
  - pipelines
  - pipelineruns
  - pipelineresources
  - conditions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - clustertasks
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-toolkit-view
  namespace: tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-toolkit-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user1
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user2
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user3
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user4
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user5
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user6
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user7
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user8
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user9
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user10
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user11
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user12
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user13
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user14
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user15
